services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mail123
  
  server:
    container_name: shremail-server
    build: ./server
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000